# roles/blob_rebuilder/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Ensure directories exists
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('openio') }}"
    group: "{{ item.group | default('openio') }}"
    mode: "{{ item.mode | default(0755) }}"
  with_items:
    - path: "/etc/gridinit.d/{{ openio_blob_rebuilder_namespace }}"
    - path: "{{ openio_blob_rebuilder_sysconfig_dir }}/{{ openio_blob_rebuilder_servicename }}"
    - path: "/var/log/oio/sds/{{ openio_blob_rebuilder_namespace }}/{{ openio_blob_rebuilder_servicename }}"
      owner: "{{ syslog_user }}"
      mode: "0750"
  tags: install

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "blob_rebuilder.conf.j2"
      dest: "{{ openio_blob_rebuilder_sysconfig_dir }}/\
        {{ openio_blob_rebuilder_servicename }}/\
        {{ openio_blob_rebuilder_servicename }}.conf"
    - src: "gridinit_blob_rebuilder.conf.j2"
      dest: "{{ openio_blob_rebuilder_gridinit_dir }}/{{ openio_blob_rebuilder_gridinit_file_prefix }}\
        {{ openio_blob_rebuilder_servicename }}.conf"
  register: _blob_rebuilder_conf

- name: restart blob_rebuilder
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart  {{ openio_blob_rebuilder_namespace }}-{{ openio_blob_rebuilder_servicename }}
  when:
    - _blob_rebuilder_conf.changed
    - not openio_blob_rebuilder_provision_only
  tags: configure
...
