# roles/blob_rebuilder/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Create the 'openio' group
  group:
    name: openio
    gid: "{{ openio_group_openio_gid | default('220')}}"
  tags: install

- name: Create the 'openio' user
  user:
    name: openio
    comment: "openio account"
    uid: "{{ openio_user_openio_uid | default('120')}}"
    group: openio
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Test directories presence
  stat:
    path: "{{ item }}"
  register: _dir
  with_items:
    - "/etc/gridinit.d/{{ openio_blob_rebuilder_namespace }}"
    - "{{ openio_blob_rebuilder_sysconfig_dir }}/oio-blob-rebuilder-{{ openio_blob_rebuilder_serviceid }}"
    - "/var/log/oio/sds/{{ openio_blob_rebuilder_namespace }}/oio-blob-rebuilder-{{ openio_blob_rebuilder_serviceid }}"

- name: Ensure directories exists
  file:
    path: "{{ item.item }}"
    state: directory
    owner: openio
    group: openio
    mode: 0755
    recurse: true
  with_items: "{{ _dir.results }}"
  when: not item.stat.exists
  tags: install

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "blob_rebuilder.conf.j2"
      dest: "{{ openio_blob_rebuilder_sysconfig_dir }}/\
        oio-blob-rebuilder-{{ openio_blob_rebuilder_serviceid }}/\
        oio-blob-rebuilder-{{ openio_blob_rebuilder_serviceid }}.conf"
    - src: "gridinit_blob_rebuilder.conf.j2"
      dest: "{{ openio_blob_rebuilder_gridinit_dir }}/{{ openio_blob_rebuilder_gridinit_file_prefix }}\
        oio-blob-rebuilder-{{ openio_blob_rebuilder_serviceid }}.conf"
  register: _blob_rebuilder_conf

- name: restart blob_rebuilder
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart  {{openio_blob_rebuilder_namespace}}-oio-blob-rebuilder-{{openio_blob_rebuilder_serviceid}}
  when:
    - _blob_rebuilder_conf.changed
    - not openio_blob_rebuilder_provision_only
  tags: configure
...
